default: &default
  adapter: mysql2
  encoding: utf8
  pool: 3
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"

development:
  <<: *default
  database: test_app_development
  timeout: <%= ENV['DATABASE_TIMEOUT'] || 5 %>

test:
  <<: *default
  database: test_app_test

staging:
  <<: *default
  database: test_app_staging

production:
  <<: *default
  database: test_app_production
